packages:
  - backend
  - frontend
  - shared

ignoredBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma

packageImportMethod: copy
