FROM mcr.microsoft.com/devcontainers/typescript-node:24

WORKDIR /workspace/backend

COPY package*.json pnpm-lock.yaml ./
RUN corepack enable && corepack prepare pnpm@latest --activate && pnpm install

EXPOSE 8000
